from fastapi import FastAPI, Body

app = FastAPI()


@app.post("/hi")
def greet(who: str = Body(embed=True)):
    return f"Hello {who}!"



if __name__ == "__main__":
    import uvicorn
    uvicorn.run("01-04--http-requests--body:app", reload=True)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("01-10--automated-documentation:app", reload=True)

# Open an autogenerated OpenAPI specification in the browser
"""
http://localhost:8000/docs
"""
# Test it with buttons "Try it out" and "Execute"
